### ISSUE TITLE
Possible incompatibility with react-native

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/appbase-js#23]
When trying to use appbase-js with react native. It will not install correctly as the dependency hyperquest depends on http and https node modules. There are also modules with this name include with react-native.

Investigate into confirming the issue and finding work arounds to this.

**Comment by divyanshu013** [comment]
React native doesn't run in a node environment. Possibly that's why we won't be able to `require` and use `http` and `https` which are core node modules. Did some finding on this and according to the [docs](https://facebook.github.io/react-native/docs/network.html) RN suggests using `fetch` or some other 3rd party like `axios`. Also [this](https://stackoverflow.com/questions/29371694/react-native-and-requirehttp) post on SO.

Perhaps a possible workaround could be to use `fetch` IMO.

**Comment by girishramnani** [comment]
But isn't hyperquest being used internally by appbase. Wouldn't using fetch
require a rewrite?

**Comment by divyanshu013** [comment]
I haven't looked into the codebase for appbase-js so I'm not sure on this

**Comment by metagrover** [comment]
We have moved to `fetch` based request in v2.

`v2.0.0-alpha-03` works with react-native.
